/*
 * sg2_err.h
 *
 *  Created on: 2 févr. 2011
 *      Author: pblanc
 */

#ifndef SG2_ERR_H_
#define SG2_ERR_H_

#define SG2_ERR_DATE_CREATE_JD_MALLOC_1 -100
#define SG2_ERR_DATE_CREATE_JD_MALLOC_2 -101
#define SG2_ERR_DATE_CREATE_JD_MALLOC_3 -102

#define SG2_ERR_DATE_CREATE_YMD_H_MALLOC_1 -210
#define SG2_ERR_DATE_CREATE_YMD_H_MALLOC_2 -211
#define SG2_ERR_DATE_CREATE_YMD_H_MALLOC_3 -212
#define SG2_ERR_DATE_CREATE_YMD_H_MALLOC_4 -213
#define SG2_ERR_DATE_CREATE_YMD_H_MALLOC_5 -214

#define SG2_ERR_DATE_CREATE_YDOY_H_MALLOC_1 -310
#define SG2_ERR_DATE_CREATE_YDOY_H_MALLOC_2 -311
#define SG2_ERR_DATE_CREATE_YDOY_H_MALLOC_3 -312
#define SG2_ERR_DATE_CREATE_YDOY_H_MALLOC_4 -313

#define SG2_ERR_DATE_JD_DELTA_TT_UT_OUTOFPERIOD -400


#endif /* SG2_ERR_H_ */
